[gestures_3]
swipe_up_3 = dbus-send --session --dest=org.gnome.Shell --type=method_call /org/gnome/Shell org.freedesktop.DBus.Properties.Set string:org.gnome.Shell string:OverviewActive variant:boolean:true
#wmctrl -k on
swipe_down_3 = dbus-send --session --dest=org.gnome.Shell --type=method_call /org/gnome/Shell org.freedesktop.DBus.Properties.Set string:org.gnome.Shell string:OverviewActive variant:boolean:false
swipe_left_3 = xdotool set_desktop --relative -- -1
swipe_right_3 = xdotool set_desktop --relative 1

[gestures_4]
swipe_up_4 = nautilus
swipe_down_4 = firefox
swipe_left_4 = xdotool set_desktop --relative -- -1
swipe_right_4 = xdotool set_desktop --relative 1
